---
vultr:
  regions:
    frankfurt:
      name: Frankfurt
  servers:
    1x1:
      name: "1024 MB RAM,25 GB SSD,1.00 TB BW"
    2x1:
      name: "2048 MB RAM,55 GB SSD,2.00 TB BW"
    4x2:
      name: "4096 MB RAM,80 GB SSD,3.00 TB BW"
