---
- name: create worker
  import_playbook: create_server.yml
  vars:
    quartermaster_server_group: workers

- hosts: workers
  remote_user: admin
  become: yes
  roles:
    - cr
    - co
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
