---
- name: create master
  import_playbook: create_server.yml
  vars:
    servrd_server_group: masters

- name: create worker
  import_playbook: create_server.yml
  vars:
    servrd_server_group: workers

- hosts: all
  remote_user: admin
  become: yes
  roles:
    - co
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
