---
- name: replace unit file(s)
  template:
    src: etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: reload kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: open required port(s)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 2379
    - 2380

- name: create required directories
  file:
    path: /etc/kubernetes
    state: directory
    mode: 0755

- name: add cluster configuration
  template:
    src: etc/kubernetes/kubeadm-config.yml.j2
    dest: /etc/kubernetes/kubeadm-config.yml
    force: yes

- run_once: yes
  block:

  - name: generate certificate authority
    command: "kubeadm init phase certs etcd-ca --config=/etc/kubernetes/kubeadm-config.yml"
  
  - name: compress certificates directory
    archive:
      path: /etc/kubernetes/pki
      dest: /tmp/pki.tar
      format: tar
  
  - name: download certificates archive
    fetch:
      src: /tmp/pki.tar
      dest: "{{ db.wd }}/pki.tar"
      flat: yes

- name: register certificate directory
  stat:
    path: /etc/kubernetes/pki
  register: certificate_directory

- block:

  - name: distribute certificates archive
    copy:
      src: "{{ db.wd }}/pki.tar"
      dest: /tmp/pki.tar

  - name: uncompress certificates archive
    unarchive:
      src: /tmp/pki.tar
      dest: /tmp/
      remote_src: yes

  - name: move certificates
    copy:
      src: /tmp/pki
      dest: /etc/kubernetes/
      remote_src: yes
  
  when: not certificate_directory.stat.exists

- name: generate certs
  command: "kubeadm init phase certs {{ item }} --config=/etc/kubernetes/kubeadm-config.yml"
  with_items:
  - etcd-server
  - etcd-peer
  - etcd-healthcheck-client
  - apiserver-etcd-client

- name: create manifests
  command: kubeadm init phase etcd local --config=/etc/kubernetes/kubeadm-config.yml

- name: delete temporary resources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/pki.tar
    - /tmp/pki
