---
- name: (containerd) create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/containerd
    - /usr/local/lib/systemd/system

- name: (containerd) download files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "https://github.com/containerd/containerd/releases/download/v{{ cr.containerd.version }}/containerd-{{ cr.containerd.version }}-linux-amd64.tar.gz"
      dest: /opt
    - url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
      dest: /usr/local/lib/systemd/system/containerd.service

- name: (containerd) unzip packages
  unarchive:
    src: "/opt/containerd-{{ cr.containerd.version }}-linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: (containerd) enable services
  systemd:
    name: containerd
    enabled: yes
    state: started
