---
- name: install runc
  import_tasks: runc.yml

- name: install cni
  import_tasks: cni.yml

- name: install crictl
  import_tasks: crictl.yml

- name: install containerd
  import_tasks: containerd.yml

- name: install docker
  import_tasks: docker.yml

- name: install cri-dockerd
  import_tasks: cri_dockerd.yml
