---
- name: open required port(s)
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: tcp
  with_items:
    - rule: allow
      port: 6443
    - rule: allow
      port: 9000

- name: install packages
  apt:
    name: haproxy

- name: add configuration
  template:
    src: etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    force: yes

- name: restart service
  systemd:
    name: haproxy
    state: restarted
