---
- name: open required port(s)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 6443

- name: install packages
  apt:
    name: haproxy

- name: add configuration
  template:
    src: etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    force: yes

- name: restart service
  systemd:
    name: haproxy
    state: restarted
