---
- name: generate peer certs
  command: "kubeadm init phase certs etcd-peer --config={{ remote_directory }}/kubeadmcfg.yml"

- name: generate peer certs
  command: "kubeadm init phase certs etcd-peer --config={{ remote_directory }}/kubeadmcfg.yml"

- name: generate healthcheck certs
  command: "kubeadm init phase certs etcd-healthcheck-client --config={{ remote_directory }}/kubeadmcfg.yml"

- name: generate apiserver client certs
  command: "kubeadm init phase certs apiserver-etcd-client --config={{ remote_directory }}/kubeadmcfg.yml"

- name: save certificates directory
  copy:
    src: /etc/kubernetes/pki
    dest: "{{ remote_directory }}"
    remote_src: yes

- name: "remove non-reusable certificates"
  command: "find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete"

- name: compress certificates directory
  archive:
    path: "{{ remote_directory }}"
    dest: "{{ remote_directory }}.tar"
    format: tar

- name: download certificates directory
  fetch:
    src: "{{ remote_directory }}.tar"
    dest: "{{ local_directory }}.tar"
    flat: yes

- name: remove certificates directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ remote_directory }}"
    - "{{ remote_directory }}.tar"