---
- hosts: localhost
  gather_facts: no
  roles:
    - node
    - node
    - node
  vars:
    node_region: frankfurt
    node_server: "2x1"
    node_groups: ["db"]

- hosts: db
  remote_user: root
  roles:
    - users
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/root/id_ecdsa

- hosts: db
  remote_user: admin
  become: yes
  roles:
    - os
    - db
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
