---
- hosts: db
  remote_user: root
  roles:
    - node
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/root/id_ecdsa

- hosts: db
  remote_user: admin
  become: yes
  roles:
    - db
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
