---
- hosts:
    - masters
    - workers
    - db
    - lb
  remote_user: root
  roles:
    - node
  vars:
    ansible_ssh_private_key_file: "{{ node_root_private_key_file | default('~/.ssh/root/id_ecdsa') }}"

- hosts:
    - masters
    - workers
    - db
  remote_user: admin
  become: yes
  roles:
    - cr
    - co
  vars:
    ansible_ssh_private_key_file: "{{ node_admin_private_key_file | default('~/.ssh/admin/id_ecdsa') }}"

- hosts: db
  remote_user: admin
  become: yes
  roles:
    - db
  vars:
    ansible_ssh_private_key_file: "{{ node_admin_private_key_file | default('~/.ssh/admin/id_ecdsa') }}"

- hosts: lb
  remote_user: admin
  become: yes
  roles:
    - lb
  vars:
    ansible_ssh_private_key_file: "{{ node_admin_private_key_file | default('~/.ssh/admin/id_ecdsa') }}"

- hosts: masters
  remote_user: admin
  become: yes
  roles:
    - master
  vars:
    ansible_ssh_private_key_file: "{{ node_admin_private_key_file | default('~/.ssh/admin/id_ecdsa') }}"

- hosts: workers
  remote_user: admin
  become: yes
  roles:
    - worker
  vars:
    ansible_ssh_private_key_file: "{{ node_admin_private_key_file | default('~/.ssh/admin/id_ecdsa') }}"
