---
- hosts:
    - masters
    - workers
  remote_user: root
  roles:
    - node
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/root/id_ecdsa

- hosts:
    - masters
    - workers
  remote_user: admin
  become: yes
  roles:
    - cr
    - co
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa

- hosts: masters
  remote_user: admin
  become: yes
  roles:
    - master
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa

- hosts: workers
  remote_user: admin
  become: yes
  roles:
    - worker
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
