---
- name: provision user(s)
  user:
    name: admin
    group: sudo
    shell: /bin/bash

- name: re-configure authorized keys
  authorized_key:
    user: admin
    state: present
    key: "{{ lookup('file', '/home/krooney/.ssh/admin/id_ecdsa.pub') }}"

- name: add private keys
  copy:
    src: /home/krooney/.ssh/admin/id_ecdsa
    dest: ~/.ssh/id_ecdsa
    mode: 0600

- name: purge authorized keys
  remote_user: root
  file:
    state: absent
    path: '/home/{{ item.name }}/.ssh/authorized_keys'
  with_items:
    - name: root

- name: update sudoer(s)
  lineinfile:
    path: '/etc/sudoers'
    regexp: '^%sudo.*ALL=\(ALL:ALL\).*'
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: override sshd config
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^.*PasswordAuthentication .*'
      line: 'PasswordAuthentication no'
    - regexp: '^.*PermitRootLogin .*'
      line: 'PermitRootLogin no'

- name: restart ssh.
  service:
    name: ssh
    state: restarted
