---
- name: (cni) create directories
  file:
    path: /opt/cni/bin
    state: directory

- name: (cni) download files
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/{{ cni.version }}/cni-plugins-linux-amd64-{{ cni.version }}.tgz"
    dest: /opt

- name: (cni) install
  unarchive:
    src: "/opt/cni-plugins-linux-amd64-{{ cni.version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
