---
- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - conntrack
      - socat
      - wget

- name: override modprode configuration
  copy:
    src: files/etc/modules-load.d/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
  register: modprode_config

- name: reload modprode
  shell: "{{ item }}"
  with_items:
    - "modprobe overlay"
    - "modprobe br_netfilter"
  when: modprode_config.changed

- name: override sysctl configuration
  copy:
    src: files/etc/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  register: sysctl_config

- name: reload sysctl
  shell: sysctl --system
  when: sysctl_config.changed

- name: override grub config
  lineinfile:
    path: "/etc/default/grub"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^GRUB_CMDLINE_LINUX=""'
      line: 'GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"'
  register: grub_config

- name: update grub
  shell: update-grub
  when: grub_config.changed

- name: override swap configuration
  replace:
    path: /etc/fstab
    regexp: '^\/swapfile'
    replace: '# /swapfile'
  register: swap_config

- name: turn off swap
  shell: "swapoff -a"
  when: swap_config.changed

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/bin
    - /etc/systemd/system/kubelet.service.d

- name: download binaries
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes.version }}/bin/linux/amd64/{{ item }}"
    dest: /usr/local/bin
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: update binary permissions
  file:
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: download configurations
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service"
      dest: /etc/systemd/system/kubelet.service
    - url: "https://raw.githubusercontent.com/kubernetes/release/v0.4.0/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf"
      dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: modify configurations
  replace:
    path: "{{ item }}"
    regexp: "/usr/bin"
    replace: "/usr/local/bin"
  with_items:
    - /etc/systemd/system/kubelet.service
    - /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: enable kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: configure port(s)
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - rule: allow
      port: 6443
      protocol: tcp

- name: configure master(s)
  import_tasks: master.yml
  when: "'masters' in group_names"

- name: configure worker(s)
  import_tasks: worker.yml
  when: "'workers' in group_names"

- name: reboot machine
  reboot:
