---
- name: initialize cluster
  shell: "kubeadm init --cri-socket=/run/containerd/containerd.sock --apiserver-advertise-address={{ ansible_default_ipv4.address }} --node-name={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16 > kubeadm.log"
  args:
    chdir: $HOME
    creates: kubeadm.log

- name: create configuration directory
  become_user: admin
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: "0755"

- name: copy cluster configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/admin/.kube/config
    remote_src: yes
    owner: admin
    group: sudo

- name: wait until cluster is ready
  command: kubectl cluster-info
  register: cluster_info
  until: ("Kubernetes control plane" in cluster_info.stdout) and ("is running" in cluster_info.stdout)
  become_user: admin
  become: no
  retries: 30
  delay: 20
  args:
    chdir: $HOME

- name: install network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  become_user: admin
  become: yes
  args:
    chdir: $HOME
