---
- name: initialize cluster
  shell: "kubeadm init --cri-socket=/run/{{ cr_deployment_type | default('cri-dockerd.sock') }} --apiserver-advertise-address={{ ansible_default_ipv4.address }} --node-name={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16 > kubeadm.log"
  args:
    chdir: $HOME
    creates: kubeadm.log

- name: create configuration directory
  file:
    path: /home/admin/.kube
    state: directory
    mode: "0755"
    owner: admin
    group: sudo

- name: copy cluster configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/admin/.kube/config
    remote_src: yes
    owner: admin
    group: sudo

- name: apply network
  block:

    - name: wait for cluster
      command: kubectl cluster-info
      register: cluster_info
      until: ("Kubernetes control plane" in cluster_info.stdout) and ("is running" in cluster_info.stdout)
      retries: 30
      delay: 20

    - name: install network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  become_user: admin
  become: yes
