---
- name: open required port(s)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 10250
    - 10257
    - 10259
    - "30000:32767"

- name: generate join command
  shell: kubeadm token create --print-join-command
  register: join_command_output
  delegate_to: "{{ groups['masters'][0] }}"

- name: add worker(s)
  shell: "{{ join_command_output.stdout }} --node-name={{ ansible_default_ipv4.address }} > node_joined.log"
  args:
    chdir: $HOME
    creates: node_joined.log
