---
- hosts: localhost
  gather_facts: no
  roles:
    - nodes
  vars:
    node_region: frankfurt
    node_groups: ["new_workers", "workers"]
    node_server: "4x2"

- hosts: new_workers
  remote_user: root
  roles:
    - users
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/root/id_ecdsa

- hosts: new_workers
  remote_user: admin
  become: yes
  roles:
    - os
    - cr
    - co
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
