---
- hosts: localhost
  gather_facts: no
  roles:
    - auth
    - { role: nodes, node_groups: ["masters"] }
    - { role: nodes, node_groups: ["workers"] }
  vars:
    node_region: frankfurt

- hosts: all
  remote_user: root
  roles:
    - users
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/root/id_ecdsa

- hosts: all
  remote_user: admin
  become: yes
  roles:
    - os
    - cr
    - co
  vars:
    ansible_ssh_private_key_file: /home/krooney/.ssh/admin/id_ecdsa
